
- name: STEP-01 Create Azure VM-UBUNTU
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - ../../../vault/vault.yaml
    - ../../vars.yaml
  tasks:
  - name: Create VM-UBUNTU
    include_tasks: pb-azure-vm-ubuntu.yaml
    tags:
      - az-vm
      - az-vm-ubuntu
