
- name: STEP-01 Create Azure VM-UBUNTU
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - ../../../vault/vault.yaml
    - ../../vars.yaml
  tasks:
  - name: Create VM-UBUNTU
    include_tasks: pb-azure-vm-ubuntu.yaml
    tags:
      - az-vm
      - az-vm-ubuntu

  - name: STEP-02 Install Docker on UBUNTU hosts"
    shell: "ansible-playbook -i /var/tmp/az-vm-ubuntu.ini pb-azure-vm-ubuntu-docker.yaml"
    # async: 10000
    # poll: 5
    # register: playlogs

  - name: Delete Ansible Dynamic Inventory file
    file:
      path: "/var/tmp/az-vm-ubuntu.ini"
      state: absent
