- name: Create Azure VM
  hosts: localhost
  connection: local

  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: RG_VM-UBUNTU-02
      name: VM-UBUNTU-02
      started: no
      
