---
- hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: R31-RG_ANSIBLE-TEST-01
        location: eastus
      register: rg
    - debug:
        var: rg
