
  - name: Register FQDN > r31-hackazon-0701.southeastasia.cloudapp.azure.com
    azure_rm_publicipaddress:
      resource_group: RG-R31_VM-BIGIP-0701
      name: r31-bigip-0701-ext-pip0
      allocation_method: Static
      domain_name: r31-hackazon-0701
    register: hackazon-0701

  - name: Register FQDN > r31-dvwa-0701.southeastasia.cloudapp.azure.com
    azure_rm_publicipaddress:
      resource_group: RG-R31_VM-BIGIP-0701
      name: r31-bigip-0701-ext-pip1
      allocation_method: Static
      domain_name: r31-dvwa-0701
    register: dvwa-0701

  - name: Register FQDN > r31-juiceshop-0701.southeastasia.cloudapp.azure.com
    azure_rm_publicipaddress:
      resource_group: RG-R31_VM-BIGIP-0701
      name: r31-bigip-0701-ext-pip2
      allocation_method: Static
      domain_name: r31-juiceshop-0701
    register: juiceshop-0701
