
  - name: Register FQDN > r31-hackazon-01.southeastasia.cloudapp.azure.com
    azure_rm_publicipaddress:
      resource_group: RG-R31_VM-BIGIP-01
      name: r31-bigip-01-ext-pip0
      allocation_method: Static
      domain_name: r31-hackazon-01
    register: hackazon-01

  - name: Register FQDN > r31-dvwa-01.southeastasia.cloudapp.azure.com
    azure_rm_publicipaddress:
      resource_group: RG-R31_VM-BIGIP-01
      name: r31-bigip-01-ext-pip1
      allocation_method: Static
      domain_name: r31-dvwa-01
    register: dvwa-01

  - name: Register FQDN > r31-juiceshop-01.southeastasia.cloudapp.azure.com
    azure_rm_publicipaddress:
      resource_group: RG-R31_VM-BIGIP-01
      name: r31-bigip-01-ext-pip2
      allocation_method: Static
      domain_name: r31-juiceshop-01
    register: juiceshop-01
