- name: STEP-01 Deploy VM-BIGP-01 using ARM template
  hosts: localhost
  connection: local
  tasks:
  - include_tasks: pb-azure-vm-bigip-01.yaml

- name: STEP-02 Create a VIP, pool and pool members
  hosts: localhost
  connection: local
  vars:
    BIGIP:
      server: r31-bigip-01.southeastasia.cloudapp.azure.com
      server_port: 443
      validate_certs: no
      user: azureuser
      password: P@ssw0rd!1234
  tasks:
  - include_tasks: pb-azure-vm-bigip-vs-pool.yaml

- name: STEP-03 Provsion F5 Module
  hosts: localhost
  connection: local
  vars:
    BIGIP:
      server: r31-bigip-01.southeastasia.cloudapp.azure.com
      server_port: 443
      validate_certs: no
      user: azureuser
      password: P@ssw0rd!1234
  tasks:
  - include_tasks: pb-azure-vm-bigip-resource-provisioning.yaml

- name: STEP-04 Register FQDN for Apps
  hosts: localhost
  connection: local
  tasks:
  - include_tasks: pb-azure-pip-fqdn.yaml
