---

- name: Create a VIP, pool and pool members
  hosts: all
  connection: local

  vars:
    BIGIP:
      server: 192.168.2.11
      server_port: 443
      validate_certs: no
      user: admin
      password: R@yanam1

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ BIGIP }}"
        lb_method: round-robin
        name: POOL-YAML-01
        monitors: http
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ BIGIP }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: POOL-YAML-01
        port: 80
      with_items:
        - host: 10.1.20.11
          name: VLAB-WEB-01
        - host: 10.1.20.12
          name: VLAB-WEB-02
      delegate_to: localhost

    - name: Create a VS
      bigip_virtual_server:
        provider: "{{ BIGIP }}"
        description: VS yaml 01
        destination: 192.168.1.20
        name: VS-YAML-01
        pool: POOL-YAML-01
        port: 80
        snat: Automap
        profiles:
          - http
      delegate_to: localhost

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        provider: "{{ BIGIP }}"
        save: yes
      delegate_to: localhost
