- name: Create Virtual Network & Subnets
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group RG_VN-F5LAB
    azure_rm_resourcegroup:
      name: RG_VN-F5LAB
      location: japanwest

  - name: Create a virtual network VN-F5LAB
    azure_rm_virtualnetwork:
      name: VN-F5LAB
      resource_group: RG_VN-F5LAB
      address_prefixes_cidr:
          - "10.1.0.0/16"

  - name: Create subnet VLAN_EXTERNAL
    azure_rm_subnet:
      name: VLAN_EXTERNAL
      virtual_network_name: VN-F5LAB
      resource_group: RG_VN-F5LAB
      address_prefix_cidr: "10.1.10.0/24"

  - name: Create subnet VLAN_INTERNAL
    azure_rm_subnet:
      name: VLAN_INTERNAL
      virtual_network_name: VN-F5LAB
      resource_group: RG_VN-F5LAB
      address_prefix_cidr: "10.1.20.0/24"

  - name: Create subnet VLAN_MGMT
    azure_rm_subnet:
      name: VLAN_MGMT
      virtual_network_name: VN-F5LAB
      resource_group: RG_VN-F5LAB
      address_prefix_cidr: "10.1.255.0/24"
