---

- name: Assign Policy to VS
  hosts: localhost
  connection: local

  vars:
    BIGIP:
      server: 192.168.1.11
      server_port: 443
      validate_certs: no
      user: admin
      password: R@yanam1

  tasks:
    - name: Assign ASM policy to VS
      bigip_virtual_server:
        provider: "{{ BIGIP }}"
        name: VS_HACKIT_01
        profiles:
          - ASM_SP_TEST_01
          - websecurity
          - http
          - tcp
      delegate_to: localhost

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        provider: "{{ BIGIP }}"
        save: yes
      delegate_to: localhost
