---

- name: Assign Policy to VS
  hosts: localhost
  connection: local

  vars:
    BIGIP:
      server: 192.168.1.11
      server_port: 443
      validate_certs: no
      user: admin
      password: R@yanam1

  tasks:
  - name: Create LTM policy for ASM
    bigip_policy:
      name: POLICY_VS_HACKIT_01
      state: present
    delegate_to: localhost

  - name: Add a rule to the new policy - Immediately published
    bigip_policy_rule:
      policy: POLICY_VS_HACKIT_01
      name: asm
      conditions:
        - type: all_traffic
      actions:
        - type: enable
          asm_policy: SP_HACKIT_01

  - name: Save the running configuration of the BIG-IP
    bigip_config:
      provider: "{{ BIGIP }}"
      save: yes
    delegate_to: localhost
