- name: Delete a resouce group
  hosts: localhost
  connection: local
  vars_files:
    - ../../vars.yaml
  tasks:
  - name: Delete a resource group UBUNTU
    azure_rm_resourcegroup:
      name: "RG-{{ azure.tag_id | upper }}_VM-UBUNTU-{{ azure.tag_vn }}{{ '%s'|format(item) }}"
      state: absent
      force: True
    with_sequence: count={{ ubuntu.instance }} format="%02d"

  - name: Delete a resource group BIGIP
    azure_rm_resourcegroup:
      name: "RG-{{ azure.tag_id | upper }}_VM-BIGIP-{{ azure.tag_vn }}{{ '%s'|format(item) }}"
      state: absent
      force: True
    with_sequence: count={{ bigip.instance }} format="%02d"
