
- name: STEP-01 Create Azure VM-UBUNTU-0701
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Create VM UBUNTU-0701
    include_tasks: pb-azure-vm-ubuntu.yaml

- name: STEP-02 Install Docker on Ubuntu host
  hosts: r31-ubuntu-0701.southeastasia.cloudapp.azure.com
  gather_facts: True
  remote_user: azureuser
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
      - name: Install Docker
        include_tasks: pb-azure-vm-ubuntu-docker.yaml

- name: STEP-03 Pull Docker Image & Create Container
  hosts: r31-ubuntu-0701.southeastasia.cloudapp.azure.com
  gather_facts: no
  remote_user: azureuser
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
      - name: Pull Docker Image & Create Container
        include_tasks: pb-azure-vm-ubuntu-docker-container.yaml
