
- name: Create Azure {{ hostvars[item].vm_name | upper }}
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - ../vault/vault.yaml
    - vars.yaml
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ azure.vn_rg | upper }}_{{ hostvars[item].vm_name | upper }}"
      location: southeastasia
      tags:
        id: 'R31'
        user: 'Bobby'
    tags:
      - az-vm
      - az-vm-centos

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ azure.vn_rg | upper }}_{{ hostvars[item].vm_name | upper }}"
      allocation_method: Static
      name: "{{ hostvars[item].vm_name | upper }}-pip"
      domain_name: "{{ hostvars[item].vm_dnslabel }}"
    register: public_ip_address
    tags:
      - az-vm
      - az-vm-centos

  - name: FQDN & Allocated public IP address
    debug:
      msg: "FQDN = {{ public_ip_address.state.dns_settings.fqdn }} , Public IP = {{ public_ip_address.state.ip_address }}"
    tags:
      - az-vm
      - az-vm-centos

  - name: Create Network Security Group
    azure_rm_securitygroup:
      resource_group: "{{ azure.vn_rg | upper }}_{{ hostvars[item].vm_name | upper }}"
      name: "{{ hostvars[item].vm_name | upper }}-nsg"
      rules:
        - name: ALLOW_ALL_IN
          protocol: "*"
          destination_port_range: "*"
          access: Allow
          priority: 4000
          direction: Inbound
        - name: ALLOW_ALL_OUT
          protocol: "*"
          destination_port_range: "*"
          access: Allow
          priority: 4000
          direction: Outbound
    tags:
      - az-vm
      - az-vm-centos

  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ azure.vn_rg | upper }}_{{ hostvars[item].vm_name | upper }}"
      name: "{{ hostvars[item].vm_name | upper }}-nic"
      virtual_network_name: '/subscriptions/{{ azure.subs }}/resourceGroups/{{ azure.vn_rg }}/providers/Microsoft.Network/virtualNetworks/{{ azure.vn_name }}'
      subnet_name: VLAN_INTERNAL
      ip_configurations:
        - name: "{{ hostvars[item].vm_name | upper }}-ip"
          private_ip_allocation_method: Static
          private_ip_address: "{{ hostvars[item].ip_int }}"
          public_ip_address_name: "{{ hostvars[item].vm_name | upper }}-pip"
      security_group: "{{ hostvars[item].vm_name | upper }}-nsg"
    tags:
      - az-vm
      - az-vm-centos

  - name: Create {{ hostvars[item].vm_name | upper }}
    azure_rm_virtualmachine:
      resource_group: "{{ azure.vn_rg | upper }}_{{ hostvars[item].vm_name | upper }}"
      name: "{{ hostvars[item].vm_name }}"
      vm_size: Standard_D2s_v3
      admin_username: azureuser
      admin_password: "{{ vault_password }}"
      ssh_public_keys:
        - path: '/home/azureuser/.ssh/authorized_keys'
          key_data: "{{ vault_sshkey }}"
      network_interfaces: "{{ hostvars[item].vm_name | upper }}-nic"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.6'
        version: latest
      tags:
        type: 'centos'
        id: 'R31'
        user: 'Bobby'
    tags:
      - az-vm
      - az-vm-centos
  loop: "{{ groups['node'] }}"
